src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/model/forum/Section.java, src/main/java/ru/java/mentor/oldranger/club/model/forum/Topic.java, src/main/java/ru/java/mentor/oldranger/club/model/user/Role.java, src/main/java/ru/java/mentor/oldranger/club/model/user/User.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/CommentService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/user/RoleService.java, src/main/java/ru/java/mentor/oldranger/club/service/user/UserStatisticService.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/RoleServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserStatisticServiceImpl.java, src/main/resources/application.properties
Data_initizlizer impl + hib.ddl.auto = create-drop
=> Data_initizlizer impl + hib.ddl.auto = create-drop

src/main/java/ru/java/mentor/oldranger/club/Application.java, src/main/java/ru/java/mentor/oldranger/club/config/SecurityConfiguration.java
=> Blocking users

src/main/java/ru/java/mentor/oldranger/club/controller/TestSystemComment.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/CommentService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java
=> create method 2. CommentService

src/main/java/ru/java/mentor/oldranger/club/controller/TestAdminController.java, src/main/java/ru/java/mentor/oldranger/club/dto/SectionsAndSubsectionsDto.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndSubsectionsRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/SectionsAndSubsectionsService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/SubsectionService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/SectionServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/SectionsAndSubsectionsServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/SubsectionServiceImpl.java, src/main/resources/static/js/sortableSectionsAndSubsections.js, src/main/resources/templates/testSortableSectionsAndSubsections.html
- добавлен SectionsAndSubsectionsDto
- сделана сортировка секций и подсекций в админке
- для проверки запустить приложение и зайти сюда localhost:8888/admin/sectionsandsubsections
=> Sortable sections and subsections

src/main/java/ru/java/mentor/oldranger/club/config/SecurityConfiguration.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestMarkDown.java, src/main/resources/templates/markdown.html
=> CKEditor 5 - markdown "/markdown"

src/main/resources/templates/markdown.html
- навесить функционал на button
- реализовать подгрузку картинок по ссылке
=> CKEditor 4.

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/config/SecurityConfiguration.java
from ROLE_UNVERIFIED to ROLE_PROSPECT.
=> Change role.

pom.xml, src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/config/WebMvcConfiguration.java, src/main/java/ru/java/mentor/oldranger/club/config/WebSocketConfig.java, src/main/java/ru/java/mentor/oldranger/club/controller/GroupChatController.java, src/main/java/ru/java/mentor/oldranger/club/controller/MainPageController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestAdminController.java, src/main/java/ru/java/mentor/oldranger/club/dao/ChatRepository/MessageRepository.java, src/main/java/ru/java/mentor/oldranger/club/model/chat/Message.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/GroupChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/ChatService.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/MessageService.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/impl/ChatServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/impl/MessageServiceImpl.java, src/main/resources/static/js/chat.js, src/main/resources/templates/chat/chat.html, src/main/resources/templates/chatSettings.html
Общий чат для всех + настраиваемое удаление сообщений по cron
=> Group Chat

src/main/java/ru/java/mentor/oldranger/club/config/SecurityConfiguration.java, src/main/java/ru/java/mentor/oldranger/club/dto/ErrorDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/InviteDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/PageableUsersDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/PasswordRecoveryDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/PasswordRecoveryStatusDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/ProfileDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/RecoveryTokenDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/UpdateProfileDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/UserStatisticDto.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/AdminRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/MainPageRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PasswordRecoveryRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ScrollableTopicsRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndSubsectionsRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SystemBlockingUsersRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/user/UserProfileService.java, src/main/java/ru/java/mentor/oldranger/club/service/user/UserStatisticService.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserProfileServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserStatisticServiceImpl.java
=> Rest controller

src/main/java/ru/java/mentor/oldranger/club/model/forum/Topic.java, src/main/java/ru/java/mentor/oldranger/club/model/forum/TopicVisitAndSubscription.java, src/main/java/ru/java/mentor/oldranger/club/model/user/User.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java
=> Rest topics

src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/BlackListServiceImpl.java
Изменил метод deleteUnlockBlock, при блокировке пользователя навсегда, при запросе на SystemBlockingUsersRestController приходил null
=> buf fix in black list

src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/BlackListServiceImpl.java
Пофиксил баг: при блокировке пользователя на время, по истечении этого времени пользователь в первый раз не мог войти.
=> Fix bag in balck list

src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserDetailsServiceImpl.java
Вход должен осуществляться и по логину, и по эмейлу.
=> login by email

src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java
Добавил в CommentRestController поиск топика по id , переименовал его в CommentAndTopicRestController
=> add to Rest find topic by id

pom.xml, src/main/java/ru/java/mentor/oldranger/club/config/SocketSecurityConfig.java, src/main/java/ru/java/mentor/oldranger/club/config/WebSocketConfig.java, src/main/java/ru/java/mentor/oldranger/club/controller/GroupChatController.java, src/main/java/ru/java/mentor/oldranger/club/controller/MainPageController.java, src/main/java/ru/java/mentor/oldranger/club/controller/PrivateChatController.java, src/main/java/ru/java/mentor/oldranger/club/dao/ChatRepository/ChatRepository.java, src/main/java/ru/java/mentor/oldranger/club/dao/ChatRepository/MessageRepository.java, src/main/java/ru/java/mentor/oldranger/club/model/chat/Chat.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PrivateChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/ChatService.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/MessageService.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/impl/ChatServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/impl/MessageServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/SecurityUtilsService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/SecurityUtilsServiceImpl.java, src/main/resources/static/js/private-chat.js, src/main/resources/templates/chat/privateChat.html
Приватный чат с доступом по токену (личные сообщения)
=> Private chat

src/main/java/ru/java/mentor/oldranger/club/controller/TestUserAvatarController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/AvatarUserRestController.java
Добавил рест контроллер для автарки пользователя
=> add RestController to UserAvatar

src/main/java/ru/java/mentor/oldranger/club/config/SearchConfig.java, src/main/java/ru/java/mentor/oldranger/club/dao/SearchRepository/Impl/SearchRepositoryImpl.java, src/main/java/ru/java/mentor/oldranger/club/dao/SearchRepository/SearchRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SearchRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/SearchService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/SearchServiceImpl.java
Сервис поиска топиков и комментариев.
=> Сервис поиска топиков и комментариев.

src/main/java/ru/java/mentor/oldranger/club/model/user/RequestInvitation.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/RegistrationRestController.java, src/main/resources/templates/confirm.html
Минимальные дополнения к предыдущей задаче по регистрации:
Изменил длину поля about me при запросе на регистрацию. Зарефакторил рест-апи, относящееся к регистрации нового пользователя.
=> New registration fixes

src/main/java/ru/java/mentor/oldranger/club/controller/ConfirmRegistrationController.java, src/main/java/ru/java/mentor/oldranger/club/controller/PasswordRecoveryController.java, src/main/java/ru/java/mentor/oldranger/club/controller/PrivateChatController.java, src/main/java/ru/java/mentor/oldranger/club/controller/RequestRegistrationController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestAdminController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestInvitationController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestScrollableTopicsController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestSystemBlockingUsers.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestSystemComment.java, src/main/java/ru/java/mentor/oldranger/club/controller/UserProfileController.java
Добавил @Deprecated к контроллерам которые дублируются в Rest
=> Depricate controllers

src/main/java/ru/java/mentor/oldranger/club/restcontroller/AvatarUserRestController.java
Переписал /api/avatar на маппинг не требующий ID, и меняющий аватар у текущего залогиненного юзера
=> refactor avatarRestController

src/main/java/ru/java/mentor/oldranger/club/controller/TestSystemComment.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SystemCommentRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/WritingBanService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/WritingBanServiceImpl.java, src/main/resources/static/js/chat.js
Дополнение к задаче по запрету определенным пользователям писать комментарии, писать в чате, создавать топики на время или на всегда. Реализован запрет на топики + метод с проверкой на бан теперь в сервисе.
=> Writing ban fix

src/main/java/ru/java/mentor/oldranger/club/dao/ForumRepository/TopicRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/TopicService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/TopicServiceImpl.java
/api/actualtopics - новое апи. Возвращает список из 10 самых популярных тем форума.
=> Actual topics

src/main/java/ru/java/mentor/oldranger/club/dto/ProfileDto.java, src/main/java/ru/java/mentor/oldranger/club/dto/UpdateProfileDto.java, src/main/java/ru/java/mentor/oldranger/club/model/user/UserProfile.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java
Исправление бага обновления профиля.
=> Bug fix user profile

src/main/java/ru/java/mentor/oldranger/club/dao/ArticleRepository/ArticleRepository.java, src/main/java/ru/java/mentor/oldranger/club/dao/ArticleRepository/ArticleTagRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/article/ArticleService.java, src/main/java/ru/java/mentor/oldranger/club/service/article/ArticleTagService.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleTagServiceImpl.java
Добавление, обновление новостей
=> work for Article

src/main/java/ru/java/mentor/oldranger/club/restcontroller/PhotoRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/media/PhotoService.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoAlbumServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoServiceImpl.java
Убрал связь между сервисами в media.
=> Lombok HotFix

src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleRestController.java, src/main/resources/config/application.properties.sample, src/main/resources/logback.xml
Редактирование статей. Создатель - неделя. Модер и админ - всегда
=> Права на редактирование статьи + фиксы к логгеру

src/main/java/ru/java/mentor/oldranger/club/restcontroller/SearchRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/SearchService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/SearchServiceImpl.java
=> Search Update

src/main/java/ru/java/mentor/oldranger/club/service/mail/impl/MailServiceImpl.java
Фикс отправки сообщений на почту.
=> Fix send message!

.gitignore, src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/config/WebMvcConfiguration.java, src/main/java/ru/java/mentor/oldranger/club/controller/GroupChatController.java, src/main/java/ru/java/mentor/oldranger/club/controller/PrivateChatController.java, src/main/java/ru/java/mentor/oldranger/club/dao/ChatRepository/ChatRepository.java, src/main/java/ru/java/mentor/oldranger/club/dao/MediaRepository/PhotoRepository.java, src/main/java/ru/java/mentor/oldranger/club/model/chat/Chat.java, src/main/java/ru/java/mentor/oldranger/club/model/media/Photo.java, src/main/java/ru/java/mentor/oldranger/club/model/utils/BanType.java, src/main/java/ru/java/mentor/oldranger/club/model/utils/WritingBan.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PhotoRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PrivateChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/TokenRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/ChatService.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/MessageService.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/impl/ChatServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/chat/impl/MessageServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/media/PhotoAlbumService.java, src/main/java/ru/java/mentor/oldranger/club/service/media/PhotoService.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoAlbumServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoServiceImpl.java, src/main/resources/static/js/private-chat.js, src/main/resources/templates/testBlockingUsers.html
Так же исправлен косяк с ломбоком: чтобы в TokenRestController сервисы помечались autowired нужно каждому сервису добавить final или "@notnull"
=> Картинки в чате должны быть прикреплены к альбому приватному

src/main/java/ru/java/mentor/oldranger/club/dao/ForumRepository/ImageCommentRepository.java, src/main/java/ru/java/mentor/oldranger/club/dto/CommentDto.java, src/main/java/ru/java/mentor/oldranger/club/model/forum/Comment.java, src/main/java/ru/java/mentor/oldranger/club/model/forum/ImageComment.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/ImageCommnetService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/ImageCommentServiceImpl.java
Добавление картинок к комментариям
=> Add image to comment

src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoAlbumServiceImpl.java
=> fix update albom

src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java
Исправил добавление фото к комментарию
=> fix imagecomment

pom.xml, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/TopicVisitAndSubscriptionServiceImpl.java
Исправлена ошибка NPE   в методе updateVisitTime
( + в POM - мелкое исправление -убрал предупреждение о повторе в dependency   java-jwt )
Подробнее:
При попытке анонимного юзера войти в топик через фронт в методе updateVisitTime выкидывается NPE, так как происходит попытка логирования действий несуществующего юзера
Чтобы ошибка наблюдалась, нужно поставить фронт
=> Исправлена ошибка NPE   в методе updateVisitTime

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/model/forum/Topic.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java
При создании топика добавление и обновление комментариев разрешаются по умолчанию, у модератора есть возможность запретить эти действия в обновлении топика.
=> Forbid adding comments to topic

src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleTagRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentToArticleRestController.java
Добавление проверки времени. Админ и модератор могут всегда редактировать сообщения у все, юзер только у себя и в течении недели. Заменены  RequestBody на RequestParam
=> Comment to article replace body

src/main/java/ru/java/mentor/oldranger/club/controller/TestCommentDtoController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/CommentService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java
-добавлен функционал отдачи комментов, начиная с конкретного коммента
-введена секьюрность. Топики или секции, защищенные от анонов, анонам больше не показываются
=> Фикс маппинга /api/topic/{topicid}

src/main/java/ru/java/mentor/oldranger/club/controller/TestNewsController.java, src/main/java/ru/java/mentor/oldranger/club/dao/ArticleRepository/ArticleRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/article/ArticleService.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleServiceImpl.java
Поиск статей по тэгам с постраничным выводом.
=> Pageable articles by tags

src/main/java/ru/java/mentor/oldranger/club/config/AuthHandler.java, src/main/java/ru/java/mentor/oldranger/club/config/SecurityConfiguration.java
-возвращает статус 200 без редиректа при успешном входе
-возвращает статус 401 и причину ошибки при неудачном входе
=> AuthHandler для работы логин-пейджа

src/main/java/ru/java/mentor/oldranger/club/model/user/Role.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/AdminRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleTagRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ChatRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentToArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/RequestInvitationRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/SecurityUtilsService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/SecurityUtilsServiceImpl.java
Методы для проверки ролей админа и модератора.
=> Admin moder role utility

src/main/java/ru/java/mentor/oldranger/club/controller/ConfirmRegistrationController.java, src/main/java/ru/java/mentor/oldranger/club/controller/PasswordRecoveryController.java, src/main/java/ru/java/mentor/oldranger/club/controller/RequestRegistrationController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestInvitationController.java, src/main/java/ru/java/mentor/oldranger/club/controller/TestUserAvatarController.java, src/main/resources/templates/confirm.html
Восстановлены ошибочно удаленные файлы
=> восстановлены ошибочно удаленные контроллеры

src/main/java/ru/java/mentor/oldranger/club/dto/CommentDto.java, src/main/java/ru/java/mentor/oldranger/club/model/media/PhotoAlbum.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PhotoAlbumRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java
1) изменил endpoint получения фоток из альбома
2) рефакторинг метода создания альбома
3) добавил id в CommentDTO
=> мелкие баг фиксы

src/main/java/ru/java/mentor/oldranger/club/restcontroller/AdminRestController.java
Добавлено описание двух параметров для **SWAGGER**
см описание тут
http://localhost:8888/api/swagger-ui/index.html?url=/api/api-docs&validatorUrl=#/Admin/getAllUsers
=> Query in admin list

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/config/SecurityConfiguration.java, src/main/java/ru/java/mentor/oldranger/club/model/article/Article.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleRestController.java
1.  /api/article/add
2.  /api/article/drafts
3.  /api/article/tag
4.  /api/article/update/{id}
=> Исправлена проверка на авторизацию

src/main/java/ru/java/mentor/oldranger/club/model/user/UserStatistic.java, src/main/resources/config/datasource.properties.sample
spring.datasource.username=test
spring.datasource.password=test
=> исправили данные

src/test/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImplTest.java, src/test/java/ru/java/mentor/oldranger/club/service/forum/impl/TopicServiceImplTest.java
добавлены тесты на методы класса TopicServiceImpl, удален ненужный  тест в классе CommentServiceImplTest
=> тесты на методы класса TopicServiceImplTest

src/test/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleServiceImplTest.java, src/test/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImplTest.java, src/test/java/ru/java/mentor/oldranger/club/service/forum/impl/TopicServiceImplTest.java
исправлены тесты CommentServiceImplTest, TopicServiceImplTest, ArticleServiceImplTest
=> Fix tests delete rest boot test

src/test/java/ru/java/mentor/oldranger/club/service/forum/impl/SectionsAndSubsectionsServiceImplTest.java, src/test/java/ru/java/mentor/oldranger/club/service/user/impl/InvitationServiceImplTest.java, src/test/java/ru/java/mentor/oldranger/club/service/utils/impl/BlackListServiceImplTest.java
InvitationService, BlackListService
=> исправил тесты классов SectionsAndSubestionsService, 

src/main/java/ru/java/mentor/oldranger/club/dto/UserAuthDTO.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserServiceImpl.java
1. Убрал private String password в UserAuthDTO;
2. Привел в соответствие метод UserAuthDTO buildUserDtoByUser(User user, boolean currentUser) в UserServiceImpl
=> Delete field  password in UserAuthDTO

src/main/resources/config/cache.properties
=> clean commit

src/test/java/ru/java/mentor/oldranger/club/AbstractTest.java, src/test/java/ru/java/mentor/oldranger/club/restcontroller/PhotoAlbumRestControllerIT.java
1. Добавил AbstractTest
2. Изменил PhotoAlbumRestControllerIT, т.к. поменялся сам PhotoAlbumRestController
=> Переделал тесты под новую логику

src/main/java/ru/java/mentor/oldranger/club/dao/MediaRepository/PhotoAlbumRepository.java, src/main/java/ru/java/mentor/oldranger/club/dto/PhotoAlbumDto.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PhotoAlbumRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoAlbumServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserServiceImpl.java
Пификсил неколько багов в логике работы альбомов. Подробнее в коммитах
=> Photo album fix bug

src/main/java/ru/java/mentor/oldranger/club/config/CaffeineCacheConfig.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SystemBlockingUsersRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/TopicService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/TopicServiceImpl.java
Изменил метод разбана пользователя
В dev не залились несколько фиксов, поправил
=> unban user

src/main/java/ru/java/mentor/oldranger/club/dao/ArticleRepository/ArticleCommentRepository.java, src/main/java/ru/java/mentor/oldranger/club/dto/ArticleCommentDto.java, src/main/java/ru/java/mentor/oldranger/club/model/comment/ArticleComment.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentToArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/article/ArticleService.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleServiceImpl.java
Поправил отображение комментов в виде дерева, не было поля id у ArticleComment
=> Древовидная структура комментов у статей

src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleServiceImpl.java
Допилена логика удаления пустых комментариев
=> Если удалить все дочерние комментарии, удаляется пустой родительский

.dockerignore, .env, .gitignore, Dockerfile, README.md, docker-compose.yml, front/.dockerignore, front/Dockerfile, front/nginx.conf, mysql/Dockerfile, pom.xml
В readme.md есть описание как это делать.
=> Теперь весь проект и окружение собираются и запускаются в контейнерах.

src/main/java/ru/java/mentor/oldranger/club/dao/ForumRepository/SectionRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndSubsectionsRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/SectionsAndSubsectionsService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/SectionServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/SectionsAndSubsectionsServiceImpl.java
Спрятал от незалогининых пользователей секции и подсекции только для пользователей
=> Поправил отображение секций и подсекций для Анонимных пользователей

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/dao/ForumRepository/SubsectionRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/SectionsAndSubsectionsServiceImpl.java
Поправил отображение секций и подсекций для Анонимных пользователей
Поправил создание топиков и подсекций
=> Скрытие секций, подсекций и топиков от Анонимов

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java
1. Fixed ability to edit user`s commentar 
2. Divided the updateComment method from CommentAndTopicRestController into a couple of methods
2. Renamed article`s name
=> https://github.com/StalnoyKapibar/Oldranger.club/pull/334/commits/fix_user_edit_comment

src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java
Поменял метод editTopic для тестирования входных параметров
=> Edit method "editTopic"

src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java
Вернуть статус 401 при попытке создания неавторизованным пользователем нового топика
=> Fix-status-500-creating-topic-unauthorized

src/main/java/ru/java/mentor/oldranger/club/restcontroller/SearchRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/SearchServiceImpl.java
Добавил ответ сервера при неверном поисковом запросе на эндпоинты 
/api/searchTopics
/api/searchArticles
=> Fix-search-result

src/main/java/ru/java/mentor/oldranger/club/restcontroller/SearchRestController.java
Добавил ответ сервера при не найденном сообщении
=> Fix-api-searchComments-server-response

src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserServiceImpl.java
Исправил ошибку редактирования профиля
=> Fix update profile

src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java
Анонимные пользователи могут видеть только открытые топики
=> Fix-getTopic-for-anon

src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/CommentService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java
Рефактор метода updateComment в CommentsAndTopicsRestContoller.
=> Refactor api/comment/update

src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/CommentService.java, src/main/java/ru/java/mentor/oldranger/club/service/forum/impl/CommentServiceImpl.java
Reverts StalnoyKapibar/Oldranger.club#347
=> Revert "Refactor api/comment/update"

src/main/java/ru/java/mentor/oldranger/club/dto/EmailDraftDto.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/AdminRestController.java
Рассылка сообщений на email по группам
=> Send to group

src/main/java/ru/java/mentor/oldranger/club/dao/ArticleRepository/ArticleTagsNodeRepository.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleTagServiceImpl.java
Исправлена ошибка, возникающая при создании статей, со вложенностью больше 6
=> Fix article depth

src/main/java/ru/java/mentor/oldranger/club/dto/RequestRegistrationDto.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/RegistrationRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/mail/MailService.java, src/main/java/ru/java/mentor/oldranger/club/service/mail/impl/MailServiceImpl.java, src/main/resources/templates/registerNewUser.html
Добавлена возможность запроса регистрации через отправку формы на почту админа
=> Register new user

src/main/java/ru/java/mentor/oldranger/club/config/AuthHandler.java, src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/dao/WritingBanRepository.java, src/main/java/ru/java/mentor/oldranger/club/dto/UserAuthDTO.java, src/main/java/ru/java/mentor/oldranger/club/model/user/User.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/AdminRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentToArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentToPhotoRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SectionsAndTopicsRestController.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/SystemBlockingUsersRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/BlackListService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/WritingBanService.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/BlackListServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/SecurityUtilsServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/utils/impl/WritingBanServiceImpl.java, src/test/java/ru/java/mentor/oldranger/club/service/chat/impl/MessageServiceImplTest.java
Авторизация заблокированного пользователя. Исправил статус ответа
=> Fix response status authorization banned user

src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserServiceImpl.java
Убарала кэш для nickName, которые были изменены на новые
=> fix changing nickName

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/dao/MediaRepository/PhotoAlbumRepository.java, src/main/java/ru/java/mentor/oldranger/club/model/media/PhotoAlbum.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/media/PhotoAlbumService.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoAlbumServiceImpl.java
Связь Альбом - Топик работает через id, а не через name
=> relation between PhotoAlbum and Topic via id, not a name

src/main/java/ru/java/mentor/oldranger/club/dao/ArticleRepository/ArticleTagsNodeRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/article/ArticleTagsNodeService.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleTagsNodeServiceImp.java
При создании новой статьи админом правильно отображается раздел(ы) статьи
=> Fix add article

src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java
=> change reference to edit email

src/main/java/ru/java/mentor/oldranger/club/config/DataInitializer.java, src/main/java/ru/java/mentor/oldranger/club/dao/MediaRepository/PhotoRepository.java, src/main/java/ru/java/mentor/oldranger/club/model/media/Photo.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/media/PhotoService.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoServiceImpl.java
Исправлен баг update комментария. Фотографии при редактирования комментария в топике отображаются корректно
=> fixed photos by editing comment in topic

src/main/java/ru/java/mentor/oldranger/club/dao/UserRepository/UserRepository.java
Логин и пароль должны регистрозависимыми
=> case sensitive login or password

src/main/java/ru/java/mentor/oldranger/club/restcontroller/SystemBlockingUsersRestController.java, src/main/resources/templates/notificationAboutBan.html
Уведомление забаненному пользователю о том, что его аккаунт был заблокирован на портале
=> notification locked user about ban

src/main/java/ru/java/mentor/oldranger/club/restcontroller/RegistrationRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/mail/MailService.java, src/main/java/ru/java/mentor/oldranger/club/service/mail/impl/MailServiceImpl.java
При запросе на регистрацию письма отправляются всем администраторам и модераторам
=> send registration request to all admins and moderators

src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java
Добавила в ссылку /profile, которая попадает на почту пользователя, чтобы он мог изменить свою почту
=> change link which goes to users mail

src/main/java/ru/java/mentor/oldranger/club/restcontroller/TokenRestController.java, src/main/resources/config/application.properties.sample
Поменяла ссылки в приглашении друга с localhost:3000 на oldranger.club
=> change reference to invite people

src/main/java/ru/java/mentor/oldranger/club/restcontroller/UserProfileRestController.java
=> deleted port

src/main/java/ru/java/mentor/oldranger/club/dao/MediaRepository/PhotoAlbumRepository.java, src/main/java/ru/java/mentor/oldranger/club/dao/UserRepository/UserRepository.java, src/main/java/ru/java/mentor/oldranger/club/restcontroller/PhotoAlbumRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/media/PhotoAlbumService.java, src/main/java/ru/java/mentor/oldranger/club/service/media/impl/PhotoAlbumServiceImpl.java, src/main/java/ru/java/mentor/oldranger/club/service/user/UserService.java, src/main/java/ru/java/mentor/oldranger/club/service/user/impl/UserServiceImpl.java
Создан новый эндпойнт, чтобы показывать пользователям портала альбомы, которые создал Админ(ы) на главной странице
=> added endpoint to show admin`s photoAlbums

src/main/java/ru/java/mentor/oldranger/club/restcontroller/ArticleTagsNodeRestController.java, src/main/java/ru/java/mentor/oldranger/club/service/article/ArticleTagsNodeService.java, src/main/java/ru/java/mentor/oldranger/club/service/article/impl/ArticleTagsNodeServiceImp.java
Task:
Добавить новый эдпоинт для обновления всего дерева(структуру статей) данные при запросе api/tags/node/tree
=> Add new endpoint to save All Tree

src/main/java/ru/java/mentor/oldranger/club/restcontroller/CommentAndTopicRestController.java
Исправил ошибку при редактировании сообщений в топике.
=> Fix edit comment chat
